"""
Django settings for tienda_stihl project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os  # Import necesario para las rutas de archivos estáticos y plantillas

# ==============================
# Build paths inside the project
# ==============================
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# Quick-start development settings
# ==============================
SECRET_KEY = 'django-insecure-jw5t(x5%cce8&j2j2af-irogwaq&)3m6w)(za802i4&-3fwhpd'
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'jcatena.pythonanywhere.com']

# ==============================
# Application definition
# ==============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'web',  # tu app principal
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Middleware de localización
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tienda_stihl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'web', 'templates')],  # ruta a templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tienda_stihl.wsgi.application'

# ==============================
# Database
# ==============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==============================
# Password validation
# ==============================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==============================
# Internationalization / i18n
# ==============================
LANGUAGE_CODE = 'es'  # idioma por defecto

# Idiomas disponibles
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
]

USE_I18N = True
USE_L10N = True
USE_TZ = True
TIME_ZONE = 'UTC'

# Carpeta donde se guardarán los archivos de traducción
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# ==============================
# Static files (CSS, JavaScript, Images)
# ==============================
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),  # carpeta donde está CSS/JS en desarrollo
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # carpeta para archivos estáticos en producción

# ==============================
# Email
# ==============================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tiendastihlcabopino@gmail.com'
EMAIL_HOST_PASSWORD = 'TU_APP_PASSWORD'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
